package com.zyx.pwdmanager.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zyx.pwdmanager.greendao.Group;
import com.zyx.pwdmanager.greendao.Item;

import com.zyx.pwdmanager.greendao.GroupDao;
import com.zyx.pwdmanager.greendao.ItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig groupDaoConfig;
    private final DaoConfig itemDaoConfig;

    private final GroupDao groupDao;
    private final ItemDao itemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        groupDaoConfig = daoConfigMap.get(GroupDao.class).clone();
        groupDaoConfig.initIdentityScope(type);

        itemDaoConfig = daoConfigMap.get(ItemDao.class).clone();
        itemDaoConfig.initIdentityScope(type);

        groupDao = new GroupDao(groupDaoConfig, this);
        itemDao = new ItemDao(itemDaoConfig, this);

        registerDao(Group.class, groupDao);
        registerDao(Item.class, itemDao);
    }
    
    public void clear() {
        groupDaoConfig.clearIdentityScope();
        itemDaoConfig.clearIdentityScope();
    }

    public GroupDao getGroupDao() {
        return groupDao;
    }

    public ItemDao getItemDao() {
        return itemDao;
    }

}
